### ISSUE TITLE
Remarkable 2

### ISSUE THREAD

**Issue by notDavid** [nickmooney/remarkable-patches#1]
Hi there, just thought i'd check first because the readme says:

> This is a set of firmware patches for the reMarkable 1 tablet

Your patch also works on the remarkable 2 tablet?

**Comment by nickmooney** [comment]
Hey notDavid,

Nope, these patches only work on the rM1. I assume the same reversing tricks I'm using to patch the rM1 firmware are applicable to the rM2, but I don't have access to a rM2.

I'm writing up some Binary Ninja scripts to help automate this process for future firmware releases. If you've got any binary reversing experience, I can let you know when I've shared those if you want to take a crack at it yourself.

Best,
Nick

**Comment by notDavid** [comment]
Hi Nick, thanks for your reply. Okay i see, fyi luckily i just found someone who wrote a patch for me: https://github.com/ddvk/remarkable-hacks/blob/master/tools/other/web_on_lo_25027.sh

> I'm writing up some Binary Ninja scripts to help automate this process for future firmware releases

That sounds like fun! I hope it works out and look forward to using it sometime in the future :)

> If you've got any binary reversing experience

Nope, binary reversing is beyond me...
